name: marp
on: [push]
jobs:
  marp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update & sudo apt-get install jq
      - id: config
        run: |
          echo "::set-output name=DIR::$(jq -r .directory config.json)"
          echo "::set-output name=FORMAT::$(jq -r .output_format config.json)"
      - run: docker run --rm -u root --init -v "$(pwd)/${{steps.config.outputs.DIR}}:/home/marp/app/" 
             -e LANG="ja_JP.UTF-8" marpteam/marp-cli index.md 
             --${{steps.config.outputs.FORMAT}} 
             -o index.${{steps.config.outputs.FORMAT}} 
             --allow-local-files

      - uses: actions/upload-artifact@v2
        with:
          name: output_doc
          path: ${{steps.config.outputs.DIR}}/index.${{steps.config.outputs.FORMAT}}