name: marp
on: [push]
jobs:
  marp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update & sudo apt-get install jq
      - id: config
        run: |
          echo "::set-output name=DIR::$(jq -r .directory config.json)"
          echo "::set-output name=FORMAT::$(jq -r .output_format config.json)"
      - run: docker run --rm -v "$(pwd):/home/marp/app/" 
             -e LANG=$LANG marpteam/marp-cli ${{steps.config.outputs.DIR}}/index.md 
             --${{steps.config.outputs.FORMAT}} 
             -o ${{steps.config.outputs.DIR}}/index.${{steps.config.outputs.FORMAT}}

      - uses: actions/upload-artifact@v2
        with:
          name: output_slide
          path: ${{steps.config.outputs.DIR}}.${{steps.config.outputs.FORMAT}}